import type { Metadata } from 'next'
import './globals.css'

import { Toaster } from 'sonner'
import ReduxProvider from '@/layouts/reduxProvider'
import MainLayout from '@/layouts/MainLayout'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>CyberForge</title>
      </head>
      <body>
        <ReduxProvider>
          <Toaster />
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
      </body>
    </html>
  )
}
