create table
  public.conversation_users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id bigint null,
    conversation_id uuid null,
    constraint conversation_users_pkey primary key (id),
    constraint conversation_users_conversation_id_fkey foreign key (conversation_id) references conversation (id),
    constraint conversation_users_user_id_fkey foreign key (user_id) references user_profiles (id)
  ) tablespace pg_default;