create table
  public.friends (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    from_user_id bigint not null,
    to_user_id bigint not null,
    status text null,
    constraint friends_pkey primary key (id),
    constraint friends_from_user_id_fkey foreign key (from_user_id) references user_profiles (id),
    constraint friends_to_user_id_fkey foreign key (to_user_id) references user_profiles (id)
  ) tablespace pg_default;
