create table
  public.conversation_messages (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    message character varying null,
    user_id bigint null,
    conversation_id uuid null,
    constraint conversation_messages_pkey primary key (id),
    constraint conversation_messages_conversation_id_fkey foreign key (conversation_id) references conversation (id),
    constraint conversation_messages_user_id_fkey foreign key (user_id) references user_profiles (id)
  ) tablespace pg_default;